### ISSUE TITLE
Create infrastructure for assigning local error codes

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#134]
I've discussed this with @paddybyers and we've agreed to start asset tracking SDK error codes from 100,000, therefore part of completing this issue needs to involve opening a PR against [ably-common/protocol/errors.json](https://github.com/ably/ably-common/blob/main/protocol/errors.json).

In terms of how this is implemented as an interface, perhaps the `ErrorInformation` data class we've introduced in https://github.com/ably/ably-asset-tracking-android/pull/114 can have a new method or getter which returns a member of a local `enum` which contains all the possible local errors which can be generated by this SDK (or the SDKs, perhaps). If the `code` is not known to the local implementation then that `enum` could have a member called something like `EXTERNAL` or perhaps `SERVICE` to indicate that the `code` needs to be inspected based on Ably codes external to asset tracking SDKs.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-763) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
see [this internal Slack thread](https://ably-real-time.slack.com/archives/C030C5YLY/p1622145881062700).

**Comment by KacperKluka** [comment]
We have reserved the `100000 - 100999` [codes range for AAT](https://github.com/ably/ably-asset-tracking-common/tree/main/specification#error-codes) and created a[ document with specific error codes](https://github.com/ably/ably-asset-tracking-common/tree/main/specification#error-codes) in the common repository, so this issue seems to be resolved
