### ISSUE TITLE
Investigate upgrading to Kotlin 1.4

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#163]
We currently explicitly specify Kotlin version 1.3.72 (April 2020), which I suspect was inherited from the Android Studio boilerplate projects when they were created.

At the time of writing this Kotlin's at latest version 1.4.21 (December 2020) - see [here](https://kotlinlang.org/releases.html). Ideally we should target the latest.

One feature which would be useful to reduce diff-to-diff noise in Kotlin files is allowing trailing commas on the end lists, for example enum definitions. If we try that at the moment we get:

> The feature "trailing commas" is only available since language version 1.4

We just need to make sure there's no reason not to bump the Kotlin version up (e.g. if Android requires lower version for some reason, perhaps).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-226) by [Unito](https://www.unito.io/learn-more)

**Comment by KacperKluka** [comment]
I've updated the Kotlin version to `1.4.21`, run the example apps, played with them a bit and all seemed to work. But when I ran the `connectedCheck` I got this error `java.lang.ClassCastException: kotlin.Unit cannot be cast to kotlin.Result`.
The problem seems to be the `Result` class and `inline class`es in general. There are some issues about that but they don't propose any solution and often they mention that the problem exists in Kotlin 1.4.30 and not in 1.4.21 :man_shrugging: Some of the issues:
- https://github.com/mockk/mockk/issues/485
- https://youtrack.jetbrains.com/issue/KT-30223
- https://youtrack.jetbrains.com/issue/KT-45259

This issue seems to only exist in the testing code. We could modify that testing code so it won't use the `Result` and all should be good. But I'm not sure if there's any major benefit of using the newest Kotlin version (besides that trailing commas) that would justify the potential danger introduced by that `Result` issue. WDYT @QuintinWillison ?

**Comment by QuintinWillison** [comment]
My preference is for us to keep this codebase using the latest Kotlin version, so I would prefer to proceed and implement (to latest Kotlin version, [which seems to be](https://kotlinlang.org/docs/releases.html#release-details) `1.4.31`, 25 February 2021).

As part of the pull request generated to fix this issue, modify the tests as needed to work around this and create a new issue, if required, for us to go back and improve them in future when perhaps things have moved forward to allow them to be improved.
