### ISSUE TITLE
Reported gaps in the information being sent

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#360]
One of early testers has reported that when they tested the integration, they observed couple of 5-7 minute periods when it looked like no data was sent from the publisher.  They say that this could be cause by loss of connection they were just driving around the city - but this still sounds suspicious enough so we should make sure everything is correct.

As potential solution I suggest to write an automated test that will ensure that SDK behaves correctly when running in a background.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-911) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
Related internal discussion: https://ably-real-time.slack.com/archives/C01EPJENRD0/p1622643318160800

**Comment by ben-xD** [comment]
Did the tester observe network loss (or reduced network quality, `E`, `3G`) for the device at any time?

**Comment by kavalerov** [comment]
The only hypothesis that was discussed internally as potential issue is that `android:foregroundServiceType` potentially wasn't declared in the manifest in the user's app. 

P.S. we also don't declare it in our example publisher app - @KacperKluka was this intentional?

**Comment by kavalerov** [comment]
> Did the tester observe network loss (or reduced network quality, E, 3G) for the device at any time?

Unfortunately no, but he wasn't actively looking at the phone as he was driving around.

**Comment by KacperKluka** [comment]
@kavalerov we didn't declare the service with `android:foregroundServiceType="location"` because we do not access or request any location information directly from the OS. We start Mapbox and register a listener for its location updates. Mapbox then starts its service that is responsible for accessing the location data from the OS and enhancing it before sending it to us. 
Therefore, I thought that Mapbox's service has that attribute set and we don't have to do it. Unfortunately, the documentation is vague and only states that if an app `accesses location information in a foreground service` it should have this attribute set. But does this matter only if you access the location data directly or does it also apply when you're receiving location data from another service? :thinking:

**Comment by kavalerov** [comment]
So, based on internal conversation - if we're not able to send a location update due to the trackable's resolution then it's getting preserved in the `skippedLocations` list. However, if we're not able to send a location update due to a network issue or some other exception then the location update is lost.  (@KacperKluka at [internal](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1623052008170400?thread_ts=1621434433.014400&cid=C01EPJENRD0))

**Comment by KacperKluka** [comment]
As I've mentioned in a [Slack thread](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1623051943170000?thread_ts=1621434433.014400&cid=C01EPJENRD0) the issue might be simpler. At the moment when sending a location update fails due to some network errors then the current location update is lost. Therefore, if there are some network issues there won't be any location updates in that period of time.

**Comment by KacperKluka** [comment]
@kavalerov given above how should we proceed with this issue? Do we want to try something as simple as just putting location updates that failed to be sent into the `skippedLocations` list? Or do we want to somehow distinguish them from the location updates that weren't sent because of the trackable resolution?
