### ISSUE TITLE
Display the horizontal accuracy of locations in the subscriber example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#533]
We send the horizontal accuracy of a location in the `accuracyHorizontal` field. This displays the accuracy of the location in meters. We should show this value in the subscriber app to let users know about the quality of location updates. 
We can either display it as a circle that would have the radius set to the accuracy value or we can change the colour of the marker if the accuracy drops below certain values.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1402) by [Unito](https://www.unito.io)

**Comment by rdeoliv** [comment]
Could we also capture the throughput and compare it to expectations? We have seen that older phones also publish less messages in general (assumed to be due to older CPU, older Android versions...). It would be good to surface a throughput rating.

I am thinking something like 60 messages per minute could be 5/5 or 5 stars and anything lower would degrate the score.

**Comment by KacperKluka** [comment]
@AndyNicks do we want to always show the accuracy circle? Or do we want to only show it when the accuracy exceeds some threshold?

**Comment by AndyNicks** [comment]
Please make the accuracy circle always visible.

**Comment by KacperKluka** [comment]
@rdeoliv I've created a new issue from your comment as it seems a bit out of the scope of location accuracy. :wink: https://github.com/ably/ably-asset-tracking-android/issues/561
