### ISSUE TITLE
Decide on "filter out" vs "batched together" for location updates

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#66]
Implementation detail but it also needs documenting.

As raised by @kavalerov [here](https://github.com/ably/ably-asset-tracking-android/pull/57#discussion_r535193313).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-87) by [Unito](https://www.unito.io/learn-more)

**Comment by kavalerov** [comment]
As discussed on the call with @paddybyers this actually should be reopened. We should be able to send the skipped locations as they will allow to provide smoother experience on the subscribing side.

**Comment by KacperKluka** [comment]
At the moment we have 2 classes that represent location updates:
- `LocationUpdate` meant for the raw location updates
- `EnhancedLocationUpdate` that extends the above `LocationUpdate` and adds specific fields for the enhanced location updates

We could add a new field to the base `LocationUpdate`. That new field will be called something like `intermediateLocations` and will hold a list of locations, that we currently filter out. Those locations should be placed in chronological order.
Then when we will return that object to the SDK client he can decide if he wants to use those intermediate locations or not.

In terms of implementation we have at least two choices for that approach:
1. Keep a list of intermediate location updates for each of the trackables independently. It's easier and faster to retrieve those locations when we need to send them, but this approach consumes more memory than the other.
2. Keep a single list of enhanced locations of the publisher and depending on the last sent location for each trackable retrieve a subset from this list that should be sent. This consumes more CPU than the previous solution because we need to find the last location for each trackable in the single locations list (which can get big in time). We can optimize i.e. we could clear the locations that are older than the oldest sent location. The advantage of this approach is that we have a history of locations that when we add a new trackable we can send a subset of the history of publisher locations to it.

WDYT?

**Comment by paddybyers** [comment]
I thought that we had agreed earlier to remove `EnhancedLocationUpdate` and only have `LocationUpdate`.

> We could add a new field to the base LocationUpdate. That new field will be called something like intermediateLocations and will hold a list of locations, that we currently filter out. Those locations should be placed in chronological order.

Agreed.

> In terms of implementation we have at least two choices for that approach:

Personally now I would go for option 1. We might have 2 or 3 trackables at any time, but not many. I don't think the added complexity of option 2 is worth it.

**Comment by kavalerov** [comment]
I agree with the first option for implementation, yes.
