### ISSUE TITLE
SLF4J reporting errors with Subscriber SDK

### ISSUE THREAD

**Issue by ikurek** [ably/ably-asset-tracking-android#673]
When using `Subscriber.Builder` from the Subscriber SDK, I've noticed this error in the logs:

```
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It seems that SLF4J fails to initialize and prints the output error when `Subscriber.start()` method is called. The error occurs both with and without `LogHandler` provided

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1955) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
We do not use SLF4J in our SDKs directly, the `LogHandler` is not using any third-party libraries. After going through the dependencies it turns out that both `Java-WebSocket` and `vcdiff-core` dependencies from `ably-android` use the `slf4j-api`.

The SLF4J is only an interface that requires another dependency to act as an implementation (e.g. Log4j). That's why the error log informs us that no implementation has been found so it will use the no-operation logger implementation.

I don't think that we should do anything about it as it's up to the users of the SDK to decide whether to use an implementation of SLF4J or not.

**Comment by QuintinWillison** [comment]
Relates to https://github.com/ably/ably-asset-tracking-android/issues/326 as there could be an argument for us to adopt SLF4J ourselves.

However, regardless, @KacperKluka is entirely correct that it would be up to the application developer to decide how to consume this log output - being the entire point of having SLF4J in the middle. 😁 

This is not a bug, however I think there is work that we could do under this issue by adding something to our readme to explain why these 'errors' are seen at runtime - and that they are normal, and can be solved by adding a logger implementation.
