### ISSUE TITLE
Consider supporting static token authentication

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#730]
Right now if users want to use a static token for authentication they have to use the dynamic callback-based token authentication and always return a static token instead of generating a new one from their backend:

```
Authentication.jwt(CLIENT_ID) {
    "static-token"
}
```
This is not very elegant and we might provide a way to provide a single static token on initialisation if this is a generally applicable use case. 

The disadvantage of static token approach is that if the static token expires (e.g. TTL) the SDK stops working and there is no way to recover from that other than restarting the SDK.

**Comment by davyskiba** [comment]
I have implemented token authentication in the demo app, and providing a “static” value through the callback does feel a bit weird.

In our case, I’m creating a delivery order with the API, and in response, I’m getting a token for the subscriber. We also have a get token endpoint defined, but since I already have a valid one, I would prefer to avoid doing an additional API call to fetch it again.

It would be awesome (at least for our demo use case) if we could set an initial token like
```
Authentication.jwt(CLIENT_ID, TOKEN_FROM_BACKEND) {
    refreshToken()
}
```

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2511
