### ISSUE TITLE
Try simulating networking problems during core use cases

### ISSUE THREAD

**Issue by jaley** [ably/ably-asset-tracking-android#865]
Add an integration level test with a controllable unreliable proxy.

Use cases to test:
* Add Trackable
* Pubish location updates
* Remove Trackable

Failures to simulate:
* Dropped connection, reconnection
* Suspend / resume
* Initial attach failure
* Attach failure on resume
* Presence enter failure, and on resume
* Presence leave failure
* Detach failure

Inspect channel / presence and trackable state throughout failures

**Comment by paddybyers** [comment]
Here are some thoughts on the specific error conditions to simulate, and what those would require in respect of proxy behaviour.

## Connection establishment failure

ws connection details are provided in the ws URL - there is no `CONNECT` message.

We need to simulate various types of connection failures, and the proxy API should enable the proxy to exhibit these conditions.

Failing indefinitely isn't a very interesting test, so these failure conditions need to be exhibited in some sequence of events where a connection does eventually succeed.

**Refusal**: direct TCP-level rejection of a connection attempt

**Declined WS connection**: the WS connection declined after connection establishment with an error frame

**Declined Ably connection**: the WS connection succeeds, but the server responds with a protocol message indicating rejection of the connection attempt:
- a `DISCONNECTED` message with a 5xx status code, or 401xx token error; subsequent connection attempts should at some point proceed successfully.
- an `ERROR` message with a 4xx status code.

**Unresponsive TCP connection**: the connection attempt just hangs

**Unresponsive Ably connection**: WS connection succeeds, but there is no protocol message response - the established WS connection just hangs.

## Connection dropped after establishment

There are failure scenarios where a transport fails after establishment.

**Unresponsive transport**: the transport is unresponsive, failing to forward frames in one or both directions, without the client seeing a close event.

**Closed WS connection**: the WS connection closes without any associated protocol message indicating disconnection or error. The client sees a WS close or error frame.

**Closed Ably transport**: there is a server to client message indicating closure of the transport, followed by WS disconnection:
- a `DISCONNECTED` message with a 5xx status code, or 401xx token error; subsequent connection attempts should at some point proceed successfully.
- an `ERROR` message with a 4xx status code.

Following disconnection, we need to simulate the following reconnection cases:

**Successful resume**: a reconnection attempt succeeds within 2 minutes, with the `CONNECTED` server response including the original `connectionId`, indicating a successful resume.

**Failed resume**: a reconnection attempt succeeds within 2 minutes, with the `CONNECTED` server response including a new `connectionId` and `error` member, indicating a failed resume. The proxy API could enable resume attempts to succeed or fail for a given `connectionId`. The proxy could simulate resume failure by modifying the value of the `resume` parameter in the connection URL so that it references a nonexisting `connectionId`.

**Successful reconnect after client suspended**: the connection is down for 2 minutes, causing the client to enter the `SUSPENDED` state, but then a reconnection attempt succeeds. The resulting connection will be a new connection (ie not resumption of the original connection).

## Channel attach failure

Again, these break down into failures on an initial channel attach attempt, and failures to reattach after resume.

**Unresponsive channel attach**: the server fails to respond to an `ATTACH` message from the client. This can be simulated by the proxy simply dropping the `ATTACH` message for a given channel name.

**Failed channel attach**: the server responds to an `ATTACH` message from the client with a message indicating failure:
- a non-retriable failure, consisting of an `ERROR` message containing the `channel` name and a 4xx status code;
- a retriable failure, consisting of an `ERROR` message containing the `channel` name and a 5xx status code.

These can be simulated by the proxy simply replying to the `ATTACH` message for a given channel name with the error message (and not forwarding the `ATTACH` message to Ably).

**Failed channel resume**: the server fails to reattach to a particular channel following a successful resume. The proxy can simulate this behaviour by replacing the server-to-client `ATTACHED` message, for a given channel name, with an `ERROR` message indicating failure.

**Server-initiated detach**: the server sends a `DETACHED` message, for a previously attached channel. The proxy can simulate this by sending a `DETACH` message to the server for the channel in question, and then forwarding the subsequent `DETACHED` response, together with an `error` member, to the client.

**Unresponsive channel detach**: the server fails to respond to a `DETACH` message from the client. This can be simulated by the proxy simply dropping the `DETACH` message for a given channel name.

**Failed channel detach**: the server responds to a `DETACH` message from the client with a message indicating failure:
- a non-retriable failure, consisting of an `ERROR` message containing the `channel` name and a 4xx status code;
- a retriable failure, consisting of an `ERROR` message containing the `channel` name and a 5xx status code.

## Presence failure

Again, these break down into failures on an initial enter attempt, and failures to reenter after resume.

**Unresponsive channel enter**: the server fails to respond to an `PRESENCE` `enter` message from the client with the initial `enter()` attempt. This can be simulated by the proxy simply dropping the `PRESENCE` message for a given channel name.

**Failed channel enter**: the server responds to an `PRESENCE` `enter` message from the client with a message indicating failure:
- a non-retriable failure, consisting of an `NACK` message containing the `channel` name and a 4xx status code;
- a retriable failure, consisting of an `NACK` message containing the `channel` name and a 5xx status code.

**Failed channel update**: the server responds to an `PRESENCE` `update` message from the client with a message indicating failure:
- a non-retriable failure, consisting of an `NACK` message containing the `channel` name and a 4xx status code;
- a retriable failure, consisting of an `NACK` message containing the `channel` name and a 5xx status code.

These can be simulated by the proxy simply replying to the `PRESENCE` message for a given channel name with the nack message (and not forwarding the `PRESENCE` message to Ably).

**Failed channel reenter on resume**: the server fails to reenter to a particular channel following a successful resume. The proxy can simulate this behaviour by replacing the server-to-client `SYNC` message, for a given channel name, with an `SYNC` message in which a given `clientId`/`connectionId`/`memberId` is absent.

**Unresponsive channel leave**: the server fails to respond to a `PRESENCE` `leave` message from the client with a `leave()`. This can be simulated by the proxy simply dropping the `PRESENCE` message for a given channel name.

**Failed channel detach**: the server responds to a `PRESENCE` `leave `message from the client requesting `leave` with a message indicating failure:
- a non-retriable failure, consisting of an `NACK` message containing the `channel` name and a 4xx status code;
- a retriable failure, consisting of an `NACK` message containing the `channel` name and a 5xx status code.

**Comment by SimonWoolf** [comment]
quick comments on a brief skim

the list here includes both conditions that the ably sdk should be handling as well as ones that the SDK user (I guess here the asset-tracking library) should be handling, I guess that's deliberate?

> 401xx token error

(4014x specifically)

> Failed channel attach ... a retriable failure, consisting of an ERROR message containing the channel name and a 5xx status code.

for channels, a retriable failure uses DETACHED action not ERROR (analagous to DISCONNECTED for connections), statusCode not looked at. (ERROR is always non-retriable for channels)

> a non-retriable failure, consisting of an ERROR message containing the channel name and a 4xx status code;

Should this be included in a list of conditions that asset-tracking should be expected to in some sense 'handle'? seems like it could result in a proxy test that fakes a fatal ERROR, and then the implementer detects `failed` channels and forces a reattach so the AAT lib continues working to make the test pass, that would be the wrong behaviour. If it was reattachable it wouldn't have been an ERROR

> Failed channel resume: the server fails to reattach to a particular channel following a successful resume. The proxy can simulate this behaviour by replacing the server-to-client ATTACHED message, for a given channel name, with an ERROR message indicating failure.

per above, retryable channel resume failure would be DETACHED or (if something's gone wrong serverside) potentially nothing.

note than in the upcoming protocol v2, the sdk will be responsible for reattaching after a resume, so the proxy test pattern will need to change -- the test will become essentially identical to the channel attach failue case so could just be folded into that

> Failed channel detach: the server responds to a DETACH message from the client with a message indicating failure:
> a non-retriable failure, consisting of an ERROR message containing the channel name and a 4xx status code;
> a retriable failure, consisting of an ERROR message containing the channel name and a 5xx status code.

channel ERROR is non-retriable, it always puts the channel into the FAILED state

I don't think I'd bother with this case -- I don't think a 'failed detach' in the sense of the server responding but leaving the channel attached is actually possible. The spec does require sdks to handle getting an ATTACHED while in the DETACHING state, but that's to handle the case of detach() called before the channel becomes attached rather than because a detach can not work. (And ofc you can get a channel ERROR at any time for an attached channel, but can't think of a situation where that'd happen specifically in response to a DETACH, rather than eg because permissions changed on the key or whatever)

> Presence: Failed channel reenter on resume

note than in the upcoming protocol v2, the sdk should unconditionally reenter after a resume irrespective of sync, so changing the sync won't change anything

> Presence: Failed channel detach

(should be 'failed channel leave')

**Comment by paddybyers** [comment]
> the list here includes both conditions that the ably sdk should be handling as well as ones that the SDK user (I guess here the asset-tracking library) should be handling, I guess that's deliberate?

yes - the aim is to ensure that the asset tracking SDK is maintaining a state that's consistent with the underlying library state (in respect of connection state, channel state, and presence)

> for channels, a retriable failure uses DETACHED action not ERROR (analagous to DISCONNECTED for connections), statusCode not looked at. (ERROR is always non-retriable for channels)

ok, thanks, I suspected that but wasn't sure

> Should this be included in a list of conditions that asset-tracking should be expected to in some sense 'handle'? seems like it could result in a proxy test that fakes a fatal ERROR, and then the implementer detects `failed` channels and forces a reattach so the AAT lib continues working to make the test pass, that would be the wrong behaviour. If it was reattachable it wouldn't have been an ERROR

No, if it's a terminal error then AAT shouldn't retry, but the aim of this feature of the proxy is to enable us to write tests that verify that


> note than in the upcoming protocol v2, the sdk will be responsible for reattaching after a resume, so the proxy test pattern will need to change -- the test will become essentially identical to the channel attach failue case so could just be folded into that

yes. I added this case because at the moment ably-java has 1.1 behaviour and expects the server to reenter.

> I don't think I'd bother with this case -- I don't think a 'failed detach' in the sense of the server responding but leaving the channel attached is actually possible

ok

> note than in the upcoming protocol v2, the sdk should unconditionally reenter after a resume irrespective of sync, so changing the sync won't change anything

sure

> (should be 'failed channel leave')

thanks

**Comment by paddybyers** [comment]
I've updated the text in the original comment

**Comment by jaley** [comment]
Thanks @paddybyers and @SimonWoolf. I've created a [sheet (internal link)](https://docs.google.com/spreadsheets/d/18BU10OZGslukWy4jNWNDdDzc3m8vviDgiTg3QW6ASPY/edit?usp=sharing) to prioritise the failure cases and track implementation. Posting it here to keep it linked to the ticket.

**Comment by jaley** [comment]
All top priority tests implemented in #866 and #886 

We can create more tickets for lower priority fault simulations after the upcoming release
