### ISSUE TITLE
Investigate `ConnectionException` thrown by `Publisher.stop` and whether we can remove it

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-android#873]
It’s not clear for callers of `Publisher.stop` what it means if it [throws `ConnectionException`](https://github.com/ably/ably-asset-tracking-android/blob/d957d6c03d157f5cfdbb8e93708a903bd98e35a2/publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt#L124), or how they should respond to it. For example, do they need to try calling it again, or is the publisher now in some terminal broken state?

Investigate whether it's possible to remove this exception, like we removed `TimeoutCancellationException` in #874. If not, describe the implications of this exception being thrown.

**Comment by jaley** [comment]
@lawrence-forooghian, With this change and #871 , will there be anything remaining in the Publisher API that we think should still through `ConnectionException`? Feels like we're converging on just making this API fully async where error handling always requires callers to monitor `StateFlows`. I guess for `stop()` there isn't an obvious thing to monitor, but I agree that it's confusing for the caller if this operation appears to fail.

**Comment by lawrence-forooghian** [comment]
After the changes you've mentioned, I think the only part of the publisher API that can throw a `ConnectionException` is `Publisher.Builder.start`. I’ve created https://github.com/ably/ably-asset-tracking-android/issues/876 to look into this.

**Comment by paddybyers** [comment]
I don't think there's any value in throwing an exception in this case. If the `leave()` fails or times out, then the publisher will still go on to clean up the attachment and (assuming this is the last trackable), the connection. It will only fail to do that tidyup if the connection itself is broken, in which case it's all moot.

**Comment by KacperKluka** [comment]
For the record:
While we declared that the `ably.close()` method throws a `ConnectionException` in reality it would never do that. That's because some time ago (namely as a side-effect of https://github.com/ably/ably-asset-tracking-android/issues/170) we changed the method that stops the connection in a way that it would never throw an exception but rather wrap it in a `Result`.

Nevertheless, the `stop()` method could still hang on the `ably.close()` indefinitely due to us waiting for the connection state to change to either `closed` or `failed`, so we should add a timeout that prevents the SDK to freeze while waiting for it to happen.
