### ISSUE TITLE
Publisher can get into a bad state if offline for > 2 minutes

### ISSUE THREAD

**Issue by jaley** [ably/ably-asset-tracking-android#906]
The `DisconnectAndSuspend` fault implementation in #886 reproduces some odd behaviour from the publisher. Notes below:

## faultDuringTracking[DisconnectAndSuspend]

* Publisher starts, connects normally, adds a trackable (so channel attached and present)
* Fault kills the connection and rejects incoming connection requests for 2 minutes
* Connection state logged as OFFLINE throughout
* Proxy comes back on after 2 mins, accepts next connection request
* AAT then logs the following:

```
[AblyConnectionStateChangeWorker] Ably connection state changed ONLINE
[ChannelConnectionStateChangeWorker] Trackable 4f1dd928-16b2-4111-be73-4175b9fb4847 connection state changed OFFLINE
[ChannelConnectionStateChangeWorker] Trackable c5c2e4d9-0b99-47dc-9d5c-85bc46c819fc connection state changed OFFLINE
'WebSocketConnectReadThread-16612' [no Looper]
[DefaultAbly] Failed to leave presence for channel tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 com.ably.tracking.ConnectionException: Unable to perform operation on channel: tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 (not currently attached). (See https://help.ably.io/error/90001 for help.)
[DefaultAbly] Failed to disconnect for trackable 4f1dd928-16b2-4111-be73-4175b9fb4847 com.ably.tracking.ConnectionException: Unable to perform operation on channel: tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 (not currently attached). (See https://help.ably.io/error/90001 for help.)
[DefaultAbly] Failed to disconnect for trackable 4f1dd928-16b2-4111-be73-4175b9fb4847 com.ably.tracking.ConnectionException: Unable to perform operation on channel: tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 (not currently attached). (See https://help.ably.io/error/90001 for help.)
[DefaultPublisher] Publisher remove operation failed com.ably.tracking.ConnectionException: Unable to perform operation on channel: tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 (not currently attached). (See https://help.ably.io/error/90001 for help.)
[DefaultPublisher] Publisher stop operation started
```

This suggests:
* Connection state is back online
* Trackables are still being reported as offline
* Something causes a `presence.leave()` and disconnect from channels
* This `presence.leave()` fails with this exception:

```
com.ably.tracking.ConnectionException: Unable to perform operation on channel: tracking:4f1dd928-16b2-4111-be73-4175b9fb4847 (not currently attached). (See https://help.ably.io/error/90001 for help.)
    at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:61)
    at com.ably.tracking.common.DefaultAbly$leavePresence$2$1.onError(Ably.kt:478)
    at io.ably.lib.transport.ConnectionManager$PendingMessageQueue.nack(ConnectionManager.java:1701)
    at io.ably.lib.transport.ConnectionManager.onNack(ConnectionManager.java:1273)
    at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:1161)
    at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:183)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
    at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:959)
    at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:912)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by deanna-lad** [comment]
The link to the corresponding Jira issue is https://ably.atlassian.net/browse/SDK-3244

**Comment by QuintinWillison** [comment]
Mentioned [here](https://github.com/ably/ably-asset-tracking-android/pull/933#issue-1552863831).

**Comment by davyskiba** [comment]
Looking through the code and logs, I've realized that the `presence.leave()` call is called as a result of the `publisher.remove()` invoked in the test. When the fault is active, the presence leave message is enqueued in the pending messages list, and once the connection is reestablished, it is sent. Then Ably responds with `NACK.`

This `NACK` might happen because the connection is dropped on the server side after 2 minutes of inactivity, and leaving presence fails because it is already left, but according to the [spec](https://sdk.ably.com/builds/ably/specification/main/features/#RTP10d) in such case, we should get `ACK` response.

**Comment by paddybyers** [comment]
@davyskiba does the `NACK` contain an error message and code?

**Comment by davyskiba** [comment]
@paddybyers it does: `Unable to perform operation on channel:(...) (not currently attached). (See https://help.ably.io/error/90001 for help`. 
When receiving the message channel is in an `attaching` state on the client side.

Full message:
> onMessage() (transport = io.ably.lib.transport.WebSocketTransport {ws://localhost:13579/?key=XE5C6g.gs0esQ%3AVF5nU6q4Q3y7q70Kv4OwZjWbbINLZ_Vdg24UynkZs0s&v=1.0&format=msgpack&resume=e91uB_oYABKaTI%21nmT0iy-XWRysf5pB-20b8c&connectionSerial=3&clientId=AatTestProxy_894f1944-4557-470b-a694-044618bff13d&heartbeats=false&agent=ably-java%2F1.2.22%20ably-asset-tracking-android-publisher-tests%2F1.5.1%20android%2F29}): nack: {"action":2,"count":1,"error":{"code":90001,"href":"https://help.ably.io/error/90001","message":"Unable to perform operation on channel: tracking:2db83e72-cfac-4f70-af6a-60dc433dca64 (not currently attached). (See https://help.ably.io/error/90001 for help.)","statusCode":404},"flags":0,"msgSerial":0,"timestamp":0}

**Comment by davyskiba** [comment]
According to logs, the queued messages and then `attach` messages are sent after reestablishing the connection.
>01-23 15:23:38.498 17084 17160 D PUBLISHING SDK IT: 909:  setState(): setting connected; reason {ErrorInfo message=Unable to recover connection: not found (7tS3o4aOdts9KVTm). (See https://help.ably.io/error/80008 for help.) code=80008 statusCode=400 href=https://help.ably.io/error/80008}
01-23 15:23:38.498 17084 17160 D PUBLISHING SDK IT: 909:  send(); action = presence
01-23 15:23:38.500 17084 17160 D PUBLISHING SDK IT: 909:  send(): presence: {"action":14,"channel":"tracking:54ddf1b1-0d1d-481d-b7bc-e35731b435aa","count":0,"flags":0,"msgSerial":0,"presence":[{"data":"{\"rawLocations\":true,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
01-23 15:23:38.511 17084 17160 D PUBLISHING SDK IT: 909:  send(); action = attach
01-23 15:23:38.513 17084 17160 D PUBLISHING SDK IT: 909:  send(): attach: {"action":10,"channel":"tracking:54ddf1b1-0d1d-481d-b7bc-e35731b435aa","count":0,"flags":720928,"timestamp":0}

This matches the code in ably-java [ConnectionManager.](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L162).

@paddybyers @jaley  I think it should be fixed in ably-java. Do we want to put in some workaround in AAT until the fix is implemented?

**Comment by ikbalkaya** [comment]
Just commenting here for visibility that https://github.com/ably/ably-java/pull/900 seems to have fixed the issue as I can see this test passes when using that ably-java

**Comment by davyskiba** [comment]
This one has been resolved with the update of `ably-java`
