### ISSUE TITLE
Remove `connect()` and `attach()` timeouts from `DefaultAbly`

### ISSUE THREAD

**Issue by jaley** [ably/ably-asset-tracking-android#948]
Currently, AAT proactively times out `ably-java` `connect()` and `attach()` operations. This is counterproductive, as `ably-java` has an internal retry mechanism for these functions, which we don't benefit from if we time them out early.

The fix should be to remove the following timeouts:
* [attach](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/Ably.kt#L880)
* [connect](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/Ably.kt#L1010)

... and then ensure that nothing else is broken by this change.

We must still observe the callback listener to ensure that we transition to the `Failed` state on terminal errors, however.

This should fix the following failing `NetworkConnectivityTest` cases in `main`:
* `faulBeforeAddingTrackable[AttachUnresponsive]`
* `faulBeforeAddingTrackable[DisconnectAndSuspend]`
* `faulBeforeAddingTrackable[TcpConnectionRefused]`
* `faulBeforeAddingTrackable[TcpConnectionUnresponsive]`
* `faulDuringTracking[TcpConnectionUnresponsive]`

**Comment by jaley** [comment]
Note this should fix #859 too.

**Comment by KacperKluka** [comment]
> The fix should be to **remove the following timeouts**
> - attach
> - connect
> 
> ... and then ensure that nothing else is broken by this change.
> **We must still observe the callback listener** to ensure that we transition to the Failed state on terminal errors, however.

If we do that then we can potentially wait indefinitely for those callback listeners to be called (unless there is a build-in timeout in the `ably-java` implementation), right? Are we okay with this @jaley? Operations affected by those methods are:
- attach
  - `Subscriber.resolutionPreference()` which is used by subscribers to request different resolutions from a publisher
  - `sendMessage()` which is used to send enhanced and raw location updates from the publisher SDK
- connect
  - `SubscriberBuilder.start()` - used by the `DefaultPublisher` when starting and connecting to Ably
  - `Publisher.add()` / `Publisher.track()` - used to start Ably connection when adding the first trackable

Regarding attach:
I've noticed that we are not triggering the `channel.attach()` but simply waiting for the channel to autonomously switch to the `attached` state. Is this correct or should we manually call `attach()` as well?

**Comment by deanna-lad** [comment]
The link to the corresponding Jira issue is https://ably.atlassian.net/browse/SDK-3279

**Comment by KacperKluka** [comment]
**Regarding add/track:**
> My understanding was that with the changes in #938 , add() and track() will return immediately, is this not the case?

That PR focuses on the `channel.attach()` and `presence.enter()` operations which are the ones always performed when adding a trackable and if only they are being invoked the `add()` will return immediately. However, when we're adding the first trackable to the publisher, it has to start an Ably connection. Right now if this needs to be done we'll be waiting for the `Ably.startConnection()` to complete and in case it takes too long a timeout is thrown. I'll change it so it will be waiting for connection result in the background 👍 

**Regarding `Subscriber.resolutionPreference()`:**
> It should be treated as non-fatal if there's a delay or problem sending this request?

I think that the subscribers should know if their request was delivered to the publisher or not, so we should give them a way to know that 🤔  

> I assume it will be retried if connectivity returns later?

We send resolution requests by updating the subscriber's presence data. So if `ably-java` retries `presence.update()` then it will happen. Otherwise, we don't have any dedicated logic to retry sending resolution requests.

I think that since this is only for the subscriber side and it has not yet caused us any issues (AFAIK at least) perhaps we could simply move the timeout up so it only affects the `Subscriber.resolutionPreference()` method and create an issue to deal with it later? WDYT? 🤔 

**Regarding `sendMessage()`:**
> It may be the case that the sendMessage() operation itself needs to be timed out because it becomes irrelevant if it wasn't possible to transmit it earlier - is this not what the skipped locations feature is for?

Yes, one of the `skippedLocation`s purpose is to collect locations that we were unable to send. However, we are not timing out the send operation itself but rather in case the send fails due to a specific error we are waiting for the channel state to change to `attached` but only for 10 seconds (the troublesome timeout).

**Regarding the `attach` timeout:**
This timeout happens because we are retrying the `channel.publish()` and `presence.update()` operations when they throw a specific "Connection resume failed" exception. Now, we want to retry on each retriable exception from Ably, so perhaps we could get rid of this mechanism completely and simply take care of retrying the operation in the `WorkerQueue` instead of doing it in the `Ably` wrapper class? 🤔

**Comment by paddybyers** [comment]
> We send resolution requests by updating the subscriber's presence data. So if `ably-java` retries `presence.update()` then it will happen. Otherwise, we don't have any dedicated logic to retry sending resolution requests.

ably-java will not retry `presence.update()`, so the subscriber library will need to do that, in the same way as for the publisher.

> I think that since this is only for the subscriber side and it has not yet caused us any issues (AFAIK at least) perhaps we could simply move the timeout up so it only affects the `Subscriber.resolutionPreference()` method and create an issue to deal with it later? WDYT? 🤔

I think that's ok - retrying for the subscriber is lower priority.

> This timeout happens because we are retrying the `channel.publish()` and `presence.update()` operations when they throw a specific "Connection resume failed" exception. Now, we want to retry on each retriable exception from Ably, so perhaps we could get rid of this mechanism completely and simply take care of retrying the operation in the `WorkerQueue` instead of doing it in the `Ably` wrapper class? 🤔

For `presence.enter()`, I assume retries are being handled as part of error handling in `track()` - is that true?

For `presence.update()` - ie presence changes that aren't resulting from addition/removal of a trackable, but some other resolution change, we should judst keep retrying after a retriable error. If an update is superseded before it has succeeded, we should abandon that and only try to make the most recent update.

For `channel.publish()` - I'm not sure there's value in retrying any individual publish - just make sure that the locations that we failed to publish are included in `skippedLocations` for the subsequent publish.

**Comment by jaley** [comment]
> move the timeout up so it only affects the Subscriber.resolutionPreference() method and create an issue to deal with it later? WDYT? 🤔

That sounds like a reasonable solution for now. We can add a ticket to revisit this later 👍 

> get rid of this mechanism completely and simply take care of retrying the operation in the WorkerQueue instead of doing it in the Ably wrapper class? 🤔

This also sounds like a good plan 👍 

I'm not sure I understand the outstanding issue with `sendMessage()`, but I think the overall behaviour should be something like:

* A request to send a location update is made asynchronously, invisible to `Publisher` user code
* If we're connected and attached, we attempt to send the message
  * we will either get a success or error callback
  * if it's an error and non-fatal, we should schedule a retry, like with `presence.enter()`, `presence.leave()`
  * if it's fatal... probably give up, detach, disconnect?
* if we're not attached and connected, we postpone sending until we are
* if a message has been waiting for a long time, we need to consider whether it's still appropriate to send that location, or record it as skipped because we have it's been superseded, etc

Does this help?

@paddybyers - might need some input from you reviewing the behaviour above

**Comment by KacperKluka** [comment]
@paddybyers 
> For presence.enter(), I assume retries are being handled as part of error handling in track() - is that true?

That's true.

@paddybyers and @jaley 
> (Paddy) 
> For channel.publish() - I'm not sure there's value in retrying any individual publish - just make sure that the locations that we failed to publish are included in skippedLocations for the subsequent publish.
> 
> (James) 
> - If we're connected and attached, we attempt to send the message
>   - if it's an error and non-fatal, we should schedule a retry, like with presence.enter(), presence.leave()

Your suggestions are a bit contradictory 😅 
Now, after a `publish()` operation fails we try it once again and if this fails then we give up, save the location in the `skippedLocations` and try to send a new location update. Is this alright? Or should we change it to actually never retry sending a location once it fails and put it in the `skippedLocations` immediately?
