### ISSUE TITLE
Wait for Ably connection to leave the "suspended" state before performing operations on Ably

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#973]
When the Ably connection (or a channel) state is `suspended` then no Ably operations will succeed. Therefore, there is no point in trying to perform any operation on Ably until the state changes to something else (like `connected`). We should use the state to prevent the SDK from performing operations on the `Ably` wrapper if the state is `suspended`.

**Comment by lawrence-forooghian** [comment]
I thought that we already did this? There's definitely at least some places in `DefaultAbly` where if the channel is suspended then it'll wait for it to attach before proceeding with the operation (I tangentially mentioned it in https://github.com/ably/ably-asset-tracking-android/issues/912).

**Comment by KacperKluka** [comment]
We had the `retryChannelOperationIfConnectionResumeFails()` but we decided that the retries should happen in the `WorkerQueue` and that we shouldn't have arbitrary timeouts on Ably operations that will be repeated automatically by the `ably-java` SDK. Here it's more about monitoring the overall Ably connection state and deciding whether to perform operations on the channels or not 🤔

**Comment by lawrence-forooghian** [comment]
As it stands, it seems like the following behaviours exist for a channel in the `SUSPENDED` state (links to tests):

- `DefaultAbly.connect()`: [immediately tries to enter presence, and fails because presence enter fails](https://github.com/ably/ably-asset-tracking-android/blob/8c4a394e9e4c1ddff07eeff032459bc32db3a546/common/src/test/java/com/ably/tracking/common/DefaultAblyTests.kt#L630-L649)
- `DefaultAbly.updatePresenceData()`: [waits for channel to enter `ATTACHED` state before performing presence update](https://github.com/ably/ably-asset-tracking-android/blob/8c4a394e9e4c1ddff07eeff032459bc32db3a546/common/src/test/java/com/ably/tracking/common/DefaultAblyTests.kt#L1311-L1333)
- `DefaultAbly.sendRawLocation()`: [waits for channel to enter `ATTACHED` state before performing publish](https://github.com/ably/ably-asset-tracking-android/blob/8c4a394e9e4c1ddff07eeff032459bc32db3a546/common/src/test/java/com/ably/tracking/common/DefaultAblyTests.kt#L3111-L3133)

Does that mean that for this issue we only need to update the behaviour of `connect()`, or have I misunderstood?

**Comment by davyskiba** [comment]
The [retryChannelOperationIfConnectionResumeFails](https://github.com/ably/ably-asset-tracking-android/pull/965/files) function used by `sendEnhancedLocation(),` `sendRawLocation(),` and `updatePresenceData()` is getting removed in [#965](https://github.com/ably/ably-asset-tracking-android/pull/965)

I think the idea behind this ticket is to check the channel state and postpone those actions at the workerQueue level

**Comment by davyskiba** [comment]
AAT is doing the following actions affected by this issue:

1. send location - currently, if this operation fails, a retry is attempted without specifying any delay, which can be immediate. If we wait for a channel to get out of the suspended state, we can get a long locations queue to send (which can require additional work to ensure order). I think the best approach here would be to postpone the retry attempt with an additional delay, i.e., 200 ms, using already implemented location retry logic  [`MAX_RETRY_COUNT = 1`](https://github.com/ably/ably-asset-tracking-android/blob/4a6678b52455ef4ace6761db6c1f915f19ce18a1/publishing-sdk/src/main/java/com/ably/tracking/publisher/LocationsPublishingState.kt#L10).
2. update presence data - used by both publisher and subscriber to exchange resolution-related data. Currently, any exception that occurs on the subscribe side is logged and thrown to the caller. On the publisher side, all exceptions are ignored. In the previous implementation, `updatePresenceData` was waiting for the channel to attach with an arbitrary timeout. In this case, we could wait indefinitely until the channel enters the connected state.
3. connect - this method wraps two operations: creating a channel and entering its presence. I would suggest separating the two, not attempting to enter presence if it cannot succeed, and using workers we already have in place to retry the enter operation.

@paddybyers @jaley, what do you think about the suggested approach to this issue?

**Comment by AndyTWF** [comment]
On 3 - this works well with the refactoring I'm doing as part of #966 . I can just tweak the worker slightly to always do a presence enter (once channel is attached) and not rely on ably.connect returning true to determine if presence is entered :)

**Comment by lawrence-forooghian** [comment]
It would be good to avoid the problems of https://github.com/ably/ably-asset-tracking-android/issues/912 (and hence close that issue) when we implement this too (that is, we should make sure that as soon as we leave the `SUSPENDED` state, we retry the operation, instead of the current behaviour of waiting to enter the `ATTACHED` state).

**Comment by davyskiba** [comment]
We agreed on the suggested solutions on a call, with an increased retry timeout to 1 second for sending location.
